title: Sphinx tutorial
description: A step-by-step tutorial for documentation generation with Sphinx
url: "https://olgarithms.github.io/sphinx-tutorial/"

remote_theme: just-the-docs/just-the-docs

heading_anchors: true

aux_links:
  "Example project":
    - "//github.com/aelsayed95/sphinxy"
aux_links_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"

enable_copy_code_button: true

gh_edit_link: true
gh_edit_link_text: "View this page on GitHub."
gh_edit_repository: "https://github.com/olgarithms/sphinx-tutorial"
gh_edit_branch: "main"
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

callouts:
  tip:
    title: Tip
    color: purple
  hint:
    title: Hint
    color: green
    opacity: 0.1

# Google Analytics Tracking
ga_tracking: G-7L8KQ9QD6S
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-remote-theme
